### PR TITLE
Filter out gov regions by default.

### PR DESCRIPTION
**Pull request by costastf**

### CODE REVIEW

**Review by aperov9 — APPROVED** [review]
LGTM

**Comment by iainelder-smg** [comment]
I would make it even simpler. No parameters. Always remove the GovCloud regions.

```python
return [
    entry.get('id', '').split(':')[1]
    for entry in response.json().get('prices')
    if entry.get('id').startswith('controltower') and not "us-gov-" in entry.get('id')
]
```

[Each AWS account is scoped to one partition](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference-arns.html).

[You cannot use IAM credentials from one partition to interact with resources in a different partition](https://docs.aws.amazon.com/whitepapers/latest/aws-fault-isolation-boundaries/partitions.html).

Those features mean an AWS account created in the `aws` partition will never be able to use a region in the `aws-us-gov` partition.

Similarly an AWS account created in the `aws-us-gov` partition will never be able to use a region in the `aws` partition.

So `enable_gov_regions=True` will never work. Since it returns the regions across all partitions, it is going to fail in the `aws` partition and in the `aws-us-gov` partition.

So for now just make it work again in the `aws` partition.

---

Later if you want to make it work in either partition you could add a check for the current partition and then build a payload that contains just the regions that belong to that partition.

You can check the current partition using [STS.GetCallerIdentity](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sts/client/get_caller_identity.html).

```python
Session().client("sts").get_caller_identity()["Arn"].split(":")[1]
```

That will return one of `aws`, `aws-us-gov`, or `aws-cn` depending on the partition you are in.

[That's how we detect the partition in botocove](https://github.com/connelldave/botocove/blob/10fb482bf0fe0da240e5cba3313597e43a62257a/botocove/cove_host_account.py#L57-L59).

```python
caller_id = self.sts_client.get_caller_identity()
self.host_account_id = caller_id["Account"]
self.host_account_partition = caller_id["Arn"].split(":")[1]
```

**Comment by costastf** [comment]
Assuming you agree with @iainelder  @aperov9 I have made the change. If you guys are ok, i can release a patch version.

**Review by iainelder — APPROVED** [review]
Looks good!

**Comment by iainelder** [comment]
@costastf , let us know when you publish a new patch version so that we can use it downstream in superwerker :-)

**Comment by costastf** [comment]
v3.1.4 is released. Thanks!

**Pull request merged**
