### PR TITLE
fixed linting errors

### PR DESCRIPTION
**Pull request by nikoizs**

### CODE REVIEW

**Comment by costastf** [comment]
Wanna tag with patch?

**Comment by nikoizs** [comment]
sure, how ? :)

**Comment by nikoizs** [comment]
:( 
remote: Permission to schubergphilis/awsapilib.git denied to nikoizs.

**Comment by costastf** [comment]
Added you as maintainer, it should work now, I thought you were already one, sorry!

**Comment by costastf** [comment]
You need to accept the invitation, check your email

**Comment by costastf** [comment]
Added nikoizs too, you might want to clear things up with your profiles. Please try again and tomorrow we figure out the profile part.

**Pull request merged**
